
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE xcp_yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via xcp_yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void xcp_yyrestart (FILE *input_file ,yyscan_t yyscanner );
void xcp_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE xcp_yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void xcp_yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void xcp_yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void xcp_yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void xcp_yypop_buffer_state (yyscan_t yyscanner );

static void xcp_yyensure_buffer_stack (yyscan_t yyscanner );
static void xcp_yy_load_buffer_state (yyscan_t yyscanner );
static void xcp_yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER xcp_yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE xcp_yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE xcp_yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE xcp_yy_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *xcp_yyalloc (yy_size_t ,yyscan_t yyscanner );
void *xcp_yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void xcp_yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer xcp_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        xcp_yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            xcp_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        xcp_yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            xcp_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define xcp_yywrap(yyscanner) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[224] =
    {   0,
    16405,16405,16423,16423,   42,   42,   44,   44,16423,16423,
       42,   42,   44,   44,16423,16423,   42,   42,   44,   44,
       47,    1,   45,   46,   46,   28,   45,   46,   26,   45,
       46,   25,   26,   45,   46,   26,   45,   46,   26,   45,
       46,   26,   45,   46,   45,   46,   32,   45,   46,   32,
       46,   31,   45,   46,   30,   45,   46,   29,   45,   46,
       20,   45,   46,    2,   20,   45,   46,    2,   46,    5,
       20,   45,   46,    3,   20,   45,   46,    4,   20,   45,
       46,   20,   45,   46,    6,   20,   45,   46,    9,   20,
       45,   46,   12,   20,   45,   46,    7,   20,   45,   46,

       14,   20,   45,   46,   20,   45,   46,   20,   45,   46,
       20,   45,   46,   10,   20,   45,   46,   20,   45,   46,
        8,   20,   45,   46,   38,   45,   46,   40,   45,   46,
       40,   46,   36,   45,   46,   37,   45,   46, 8231,   45,
       46, 8231,   45,   46, 8231,   45,   46,   38,   45,   46,
       35,   45,   46,   35,   45,   46,   35,   45,   46,   34,
       45,   46,   33,   34,   45,   46,   33,   46,   42,   45,
       46,   42,   46,   41,   45,   46,   42,   45,   46,   44,
       45,   46,   44,   46,   43,   45,   46,   44,   45,   46,
       27,   45,   46, 8213,   22,   29,    2,   19,   11,   13,

       38,   38, 8231,   38,   38,   35,   35,   35,   35,   42,
       42,   42,   42,   44,   44,   44,   44,   23,   24,   15,
       18,   16,   17
    } ;

static yyconst flex_int16_t yy_accept[150] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    3,    3,    3,
        3,    3,    3,    4,    5,    5,    5,    5,    5,    5,
        5,    6,    7,    8,    9,   10,   11,   11,   11,   11,
       11,   11,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   22,   25,   26,   29,   32,   36,   39,
       42,   45,   47,   50,   52,   55,   58,   61,   64,   68,
       70,   74,   78,   82,   85,   89,   93,   97,  101,  105,
      108,  111,  114,  118,  121,  125,  128,  131,  133,  136,
      139,  142,  145,  148,  151,  154,  157,  160,  163,  167,

      169,  172,  174,  177,  180,  183,  185,  188,  191,  194,
      195,  195,  195,  196,  197,  198,  199,  200,  201,  201,
      201,  201,  201,  202,  203,  204,  205,  206,  207,  208,
      209,  210,  211,  212,  213,  214,  215,  216,  217,  218,
      219,  220,  220,  220,  221,  222,  223,  224,  224
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,    1,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    1,   15,
       16,   17,    1,    1,   18,    1,    1,   19,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   20,   21,    1,
        1,   22,    1,   23,    1,    1,    1,    1,    1,    1,
        1,   24,    1,   25,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,   26,    1,    1,    1,    1,   27,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   28,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[29] =
    {   0,
        1,    2,    3,    4,    1,    5,    2,    2,    1,    1,
        1,    1,    1,    6,    6,    6,    6,    1,    1,    1,
        1,    1,    1,    1,    6,    1,    1,    6
    } ;

static yyconst flex_int16_t yy_base[164] =
    {   0,
      343,  342,  341,  340,    0,   19,   39,   51,  339,  338,
       64,    0,   92,    0,  337,  336,  118,    0,    3,    5,
       11,   20,   24,  120,    0,    0,  335,  334,    0,    0,
       53,  122,  124,  133,  135,  136,    0,    0,  333,  332,
      331,  330,  147,  159,  148,  160,  150,  162,  329,  328,
      327,  326,  328,  347,  347,  347,  347,    0,  307,  305,
      303,  347,  347,  347,  347,  347,  311,  347,   14,   23,
      347,  347,  347,  168,  347,  347,  300,  347,  287,  276,
      222,  219,  347,  213,  347,  213,  347,  347,  347,  347,
      347,  218,  216,  186,   14,   17,    0,  347,  347,  347,

      201,  165,  347,  212,  159,  158,  347,  214,  347,  347,
      160,  150,    0,  156,  175,  347,  347,  347,  139,  124,
      178,  131,  116,    0,  347,  107,    0,   21,    0,    0,
        0,   98,  215,   33,  218,   25,  220,   21,  221,    0,
        0,  226,  228,  347,  347,  347,  347,  347,  245,  251,
      257,  263,  269,  275,  281,  287,  293,   42,   13,  299,
      305,  311,  317
    } ;

static yyconst flex_int16_t yy_def[164] =
    {   0,
      149,  149,  150,  150,  151,  151,  152,  152,  152,  152,
      148,   11,  148,   13,  152,  152,  152,   17,  153,  153,
      154,  154,  155,  155,   13,   13,  152,  152,   17,   17,
      153,  153,  154,  154,  155,  155,   13,   13,  152,  152,
      152,  152,  153,  153,  154,  154,  155,  155,  156,  156,
      152,  152,  148,  148,  148,  148,  148,  157,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  158,  148,  148,  148,  148,
      148,  148,  148,  148,  159,  159,   96,  148,  148,  148,

      160,  160,  148,  161,  162,  162,  148,  163,  148,  148,
      148,  148,  157,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  158,   94,  148,  158,   94,  159,   96,   96,
      128,  160,  161,  160,  161,  162,  163,  162,  163,  157,
      157,  148,  148,  148,  148,  148,  148,    0,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148
    } ;

static yyconst flex_int16_t yy_nxt[376] =
    {   0,
      148,  148,   55,  148,   99,  100,   99,  100,   58,   99,
       99,   99,   99,  102,  103,  115,  115,   59,  128,   60,
       61,   55,  102,  103,  115,  115,  106,   58,  129,  107,
      130,  129,  131,  130,  104,  129,   59,  130,   60,   61,
       63,   64,  123,  104,  137,   63,   63,  108,  137,   65,
       66,   67,   63,   64,   99,  100,  133,   63,   63,   99,
       99,   65,   66,   67,   68,   69,   70,   68,   71,   68,
       72,   73,   74,   75,   68,   68,   68,   76,   77,   78,
       79,   80,   68,   81,   82,   68,   68,   68,   83,   84,
       68,   85,   86,   87,   88,   89,   86,   90,   87,   87,

       86,   86,   86,   86,   86,   91,   92,   91,   93,   86,
       86,   86,   86,   86,   86,   94,   91,   86,   86,   91,
       55,  133,  106,   99,  100,  107,  102,  103,   99,   99,
      124,   95,   96,   95,   97,  102,  103,  106,  106,  124,
      107,  107,   95,  108,  145,   95,  143,  104,   99,  100,
      102,  103,  106,   99,   99,  107,  104,  142,  108,  108,
       99,  100,  102,  103,  106,   99,   99,  107,  114,  116,
      116,  104,  141,  108,  116,  116,  115,  115,  140,  144,
      144,  137,  137,  104,  144,  108,  126,  123,  133,  123,
      126,  123,  123,  123,  126,  126,  126,  126,  126,  123,

      123,  123,  123,  126,  126,  126,  126,  126,  126,  127,
      123,  126,  126,  123,  132,  132,  136,  132,  132,  136,
      132,  132,  136,  136,  133,  136,  136,  146,  146,  147,
      147,  125,  146,  125,  147,  135,  124,  139,  135,  122,
      121,  135,  120,  139,  139,   54,   54,   54,   54,   54,
       54,   56,   56,   56,   56,   56,   56,   57,   57,   57,
       57,   57,   57,   62,   62,   62,   62,   62,   62,   98,
       98,   98,   98,   98,   98,  101,  101,  101,  101,  101,
      101,  105,  105,  105,  105,  105,  105,  109,  109,  109,
      109,  109,  109,  110,  110,  119,  110,  110,  110,  132,

      132,  132,  118,  132,  132,  134,  134,  134,  134,  134,
      134,  136,  136,  136,  136,  117,  136,  138,  138,  138,
      138,  138,  138,  114,  113,  112,  111,  148,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   53,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148
    } ;

static yyconst flex_int16_t yy_chk[376] =
    {   0,
        0,    0,    5,    0,   19,   19,   20,   20,    5,   19,
       19,   20,   20,   21,   21,   69,   69,    5,  159,    5,
        5,    6,   22,   22,   70,   70,   23,    6,   95,   23,
       95,   96,   96,   96,   21,  128,    6,  128,    6,    6,
        7,    7,  158,   22,  138,    7,    7,   23,  136,    7,
        7,    7,    8,    8,   31,   31,  134,    8,    8,   31,
       31,    8,    8,    8,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       17,  132,   24,   32,   32,   24,   33,   33,   32,   32,
      126,   17,   17,   17,   17,   34,   34,   35,   36,  123,
       35,   36,   17,   24,  122,   17,  120,   33,   43,   43,
       45,   45,   47,   43,   43,   47,   34,  119,   35,   36,
       44,   44,   46,   46,   48,   44,   44,   48,  114,   74,
       74,   45,  112,   47,   74,   74,  115,  115,  111,  121,
      121,  106,  105,   46,  121,   48,   94,   94,  102,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,

       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,  104,  104,  108,  133,  133,  108,
      135,  135,  137,  139,  101,  137,  139,  142,  142,  143,
      143,   93,  142,   92,  143,  104,   86,  108,  133,   84,
       82,  135,   81,  137,  139,  149,  149,  149,  149,  149,
      149,  150,  150,  150,  150,  150,  150,  151,  151,  151,
      151,  151,  151,  152,  152,  152,  152,  152,  152,  153,
      153,  153,  153,  153,  153,  154,  154,  154,  154,  154,
      154,  155,  155,  155,  155,  155,  155,  156,  156,  156,
      156,  156,  156,  157,  157,   80,  157,  157,  157,  160,

      160,  160,   79,  160,  160,  161,  161,  161,  161,  161,
      161,  162,  162,  162,  162,   77,  162,  163,  163,  163,
      163,  163,  163,   67,   61,   60,   59,   53,   52,   51,
       50,   49,   42,   41,   40,   39,   28,   27,   16,   15,
       10,    9,    4,    3,    2,    1,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148
    } ;

#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yyg->yy_full_match; /* restore poss. backed-over text */ \
yyg->yy_lp = yyg->yy_full_lp; /* restore orig. accepting pos. */ \
yyg->yy_state_ptr = yyg->yy_full_state; /* restore orig. state */ \
yy_current_state = *yyg->yy_state_ptr; /* restore curr. state */ \
++yyg->yy_lp; \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "../src/clients/lib/xmmsclient/collparser/scanner.l"
/*  XMMS2 - X Music Multiplexer System
 *  Copyright (C) 2003-2011 XMMS2 Team
 *
 *  PLUGINS ARE NOT CONSIDERED TO BE DERIVED WORK !!!
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 */
#define YY_NO_INPUT 1
#line 27 "../src/clients/lib/xmmsclient/collparser/scanner.l"
#include <stdio.h>
#include "utils_priv.h"
#include "collparser_priv.h"
#include "parser.tab.h"

#ifdef YY_BREAK
# undef YY_BREAK
#endif
#define YY_BREAK

/* #define SC_DEBUG printf */
#define SC_DEBUG(x, ...) (void)(0)

#define BEGIN_STR(orig,tgt) do { \
	switch (YY_START) { \
		case prop##orig: \
			BEGIN (prop##tgt); \
			break; \
		case strprop##orig: \
			BEGIN (strprop##tgt); \
			break; \
		case string##orig: \
			BEGIN (string##tgt); \
			break; \
	} \
} while (0)

static void _start_loc (YYLTYPE *llocp);
static void _update_loc (YYLTYPE *llocp, const char *data);
static void _set_loc (YYLTYPE *llocp, const char *data);





















/* ^^^ Unused. Only to avoid error in BEGIN_STR macros. */





#line 675 "<stdout>"

#define INITIAL 0
#define binaryFilter 1
#define checkOP 2
#define idseq 3
#define opEOF 4
#define parse 5
#define prop 6
#define propEOF 7
#define propFIL 8
#define propINIT 9
#define propQ 10
#define propSQ 11
#define string 12
#define stringEOF 13
#define stringFIL 14
#define stringINIT 15
#define stringQ 16
#define stringSQ 17
#define strprop 18
#define strpropEOF 19
#define strpropFIL 20
#define strpropINIT 21
#define strpropQ 22
#define strpropSQ 23
#define unaryFilter 24
#define universeEOF 25

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE xmmsv_collparser_t *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    yy_state_type *yy_state_buf;
    yy_state_type *yy_state_ptr;
    char *yy_full_match;
    int yy_lp;

    /* These are only needed for trailing context rules,
     * but there's no conditional variable for that yet. */
    int yy_looking_for_trail_begin;
    int yy_full_lp;
    int *yy_full_state;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int xcp_yylex_init (yyscan_t* scanner);

int xcp_yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int xcp_yylex_destroy (yyscan_t yyscanner );

int xcp_yyget_debug (yyscan_t yyscanner );

void xcp_yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE xcp_yyget_extra (yyscan_t yyscanner );

void xcp_yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *xcp_yyget_in (yyscan_t yyscanner );

void xcp_yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *xcp_yyget_out (yyscan_t yyscanner );

void xcp_yyset_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t xcp_yyget_leng (yyscan_t yyscanner );

char *xcp_yyget_text (yyscan_t yyscanner );

int xcp_yyget_lineno (yyscan_t yyscanner );

void xcp_yyset_lineno (int line_number ,yyscan_t yyscanner );

int xcp_yyget_column  (yyscan_t yyscanner );

void xcp_yyset_column (int column_no ,yyscan_t yyscanner );

YYSTYPE * xcp_yyget_lval (yyscan_t yyscanner );

void xcp_yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *xcp_yyget_lloc (yyscan_t yyscanner );
    
        void xcp_yyset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int xcp_yywrap (yyscan_t yyscanner );
#else
extern int xcp_yywrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int xcp_yylex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int xcp_yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 97 "../src/clients/lib/xmmsclient/collparser/scanner.l"


#line 955 "<stdout>"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! yyg->yy_state_buf )
            yyg->yy_state_buf = (yy_state_type *)xcp_yyalloc(YY_STATE_BUF_SIZE  ,yyscanner);
            if ( ! yyg->yy_state_buf )
                YY_FATAL_ERROR( "out of dynamic memory in xcp_yylex()" );

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			xcp_yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				xcp_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		xcp_yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;

		yyg->yy_state_ptr = yyg->yy_state_buf;
		*yyg->yy_state_ptr++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 149 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yyg->yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 347 );

yy_find_action:
		yy_current_state = *--yyg->yy_state_ptr;
		yyg->yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yyg->yy_lp && yyg->yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yyg->yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yyg->yy_looking_for_trail_begin )
					{
					if ( yy_act == yyg->yy_looking_for_trail_begin )
						{
						yyg->yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yyg->yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yyg->yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yyg->yy_full_match = yy_cp;
					yyg->yy_full_state = yyg->yy_state_ptr;
					yyg->yy_full_lp = yyg->yy_lp;
					break;
					}
				++yyg->yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yyg->yy_state_ptr;
			yyg->yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */

case YY_STATE_EOF(INITIAL):
#line 100 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		if (!yyextra->scanner_context->started) {
			yyextra->scanner_context->started = 1;
			BEGIN (parse);
			break;
		}
		yyterminate ();
		break;
	}
	YY_BREAK
case 1:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 109 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		yyextra->scanner_context->started = 1;
		BEGIN (parse);
		break;
	}
	YY_BREAK


case YY_STATE_EOF(parse):
#line 117 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_start_loc (yylloc);
		/* Ensure an EOF is emitted for each openned sub group. */
		if (xcp_scanner_dec_group (yyextra) <= 0) {
			BEGIN (INITIAL);
		}
		return TOKEN_EOF;
	}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 125 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		break;
	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 129 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		yylval->group = xcp_scanner_inc_group (yyextra);
		return TOKEN_GROUP_OPEN;
	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 134 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		yylval->group = xcp_scanner_dec_group (yyextra);
		return TOKEN_GROUP_CLOSE;
	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 139 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (idseq);
		return TOKEN_SYMBOL_ID;
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 144 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (unaryFilter);
		return TOKEN_FILTER_HAS;
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 149 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (binaryFilter);
		return TOKEN_FILTER_EQUAL;
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 154 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (binaryFilter);
		return TOKEN_FILTER_MATCH_GLOB;
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 159 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (binaryFilter);
		return TOKEN_FILTER_MATCH;
	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 164 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (binaryFilter);
		return TOKEN_FILTER_TOKEN;
	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 169 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (binaryFilter);
		return TOKEN_FILTER_LESSEQUAL;
	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 174 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (binaryFilter);
		return TOKEN_FILTER_LESS;
	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 179 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (binaryFilter);
		return TOKEN_FILTER_GREATEREQUAL;
	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 184 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (binaryFilter);
		return TOKEN_FILTER_GREATER;
	}
	YY_BREAK
case 15:
/* rule 15 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 189 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		return TOKEN_OPERATOR_OR;
	}
	YY_BREAK
case 16:
/* rule 16 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 193 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		return TOKEN_OPERATOR_AND;
	}
	YY_BREAK
case 17:
/* rule 17 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 197 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		return TOKEN_OPERATOR_NOT;
	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 201 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		BEGIN (stringINIT);
		return TOKEN_REFERENCE;
	}
	YY_BREAK
case 19:
/* rule 19 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 206 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		return TOKEN_UNIVERSE;
	}
	YY_BREAK
case 20:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 210 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		BEGIN (checkOP);
		break;
	}
	YY_BREAK


case 21:
YY_RULE_SETUP
#line 217 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{ /* ; can't be a space here. */
		BEGIN (strpropINIT);
		break;
	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 221 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{ /* Matched only if followed by EOF */
		_set_loc (yylloc, yytext);
		BEGIN (opEOF);
		return TOKEN_OPERATOR_OR;
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 226 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{ /* Matched only if followed by EOF */
		_set_loc (yylloc, yytext);
		BEGIN (opEOF);
		return TOKEN_OPERATOR_AND;
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 231 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{ /* Matched only if followed by EOF */
		_set_loc (yylloc, yytext);
		BEGIN (opEOF);
		return TOKEN_OPERATOR_NOT;
	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 236 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{ /* Matched only if followed by EOF */
		_set_loc (yylloc, yytext);
		BEGIN (universeEOF);
		return TOKEN_UNIVERSE;
	}
	YY_BREAK
case 26:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 241 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		BEGIN (strpropINIT);
		break;
	}
	YY_BREAK


case YY_STATE_EOF(universeEOF):
#line 248 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_start_loc (yylloc);
		BEGIN (parse);
		return TOKEN_EOF_UNIVERSE;
	}
	YY_BREAK


case YY_STATE_EOF(opEOF):
#line 256 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_start_loc (yylloc);
		BEGIN (parse);
		return TOKEN_EOF_OPERATOR;
	}
	YY_BREAK


case YY_STATE_EOF(unaryFilter):
#line 264 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_start_loc (yylloc);
		BEGIN (parse);
		return TOKEN_EOF_FILTER;
	}
	YY_BREAK
case 27:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 269 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		BEGIN (propINIT);
		break;
	}
	YY_BREAK


case YY_STATE_EOF(binaryFilter):
#line 276 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_start_loc (yylloc);
		BEGIN (parse);
		return TOKEN_EOF_FILTER;
	}
	YY_BREAK
case 28:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 281 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		BEGIN (stringINIT);
		break;
	}
	YY_BREAK


case YY_STATE_EOF(idseq):
#line 288 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_start_loc (yylloc);
		BEGIN (parse);
		return TOKEN_EOF_SEQUENCE;
	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 293 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		yylval->ival = atoi (yytext);
		return TOKEN_ID;
	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 298 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		return TOKEN_ID_RANGE;
	}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 302 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_set_loc (yylloc, yytext);
		return TOKEN_ID_SEQUENCE;
	}
	YY_BREAK
case 32:
/* rule 32 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 306 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		BEGIN (parse);
		break;
	}
	YY_BREAK


case YY_STATE_EOF(strpropINIT):
case YY_STATE_EOF(propINIT):
case YY_STATE_EOF(stringINIT):
#line 313 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{ /* Initialize the string buffer. */
		_start_loc (yylloc);
		xcp_scanner_string_buffer_init (yyextra);
		BEGIN_STR (INIT,);
		break;
	}
	YY_BREAK
case 33:
/* rule 33 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 319 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{ /* Prevent odd side-effects. */
		BEGIN (parse);
		return TOKEN_ERR;
	}
	YY_BREAK
case 34:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 323 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{ /* Initialize the string buffer. and select next context */
		_start_loc (yylloc);
		xcp_scanner_string_buffer_init (yyextra);
		BEGIN_STR (INIT,);
		break;
	}
	YY_BREAK


case 35:
YY_RULE_SETUP
#line 332 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_update_loc (yylloc, yytext);
		xcp_scanner_string_buffer_append (yyextra, yytext);
		BEGIN_STR (FIL,);
		break;
	}
	YY_BREAK


case YY_STATE_EOF(prop):
case YY_STATE_EOF(strprop):
case YY_STATE_EOF(string):
#line 341 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		int start = YY_START;
		BEGIN_STR (,EOF);
		xcp_scanner_string_buffer_unescape (yyextra);
		yylval->str = xcp_scanner_string_buffer_steal (yyextra);
		if (start == prop) {
			return TOKEN_PROPERTY;
		} else {
			return TOKEN_STRING;
		}
	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 352 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_update_loc (yylloc, yytext);
		BEGIN_STR (,Q);
		break;
	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 357 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_update_loc (yylloc, yytext);
		BEGIN_STR (,SQ);
		break;
	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 362 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_update_loc (yylloc, yytext);
		xcp_scanner_string_buffer_append (yyextra, yytext);
		break;
	}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 367 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		if (YY_START == strprop) {
			BEGIN (parse);
			xcp_scanner_string_buffer_unescape (yyextra);
			yylval->str = xcp_scanner_string_buffer_steal (yyextra);
			return TOKEN_PROPERTY;
		} else {
			BEGIN_STR (,FIL);
		}
		break;
	}
	YY_BREAK
case 40:
/* rule 40 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 378 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		int start = YY_START;
		BEGIN (parse);
		xcp_scanner_string_buffer_unescape (yyextra);
		yylval->str = xcp_scanner_string_buffer_steal (yyextra);
		if (start == prop) {
			return TOKEN_PROPERTY;
		} else {
			return TOKEN_STRING;
		}
	}
	YY_BREAK


case YY_STATE_EOF(propEOF):
case YY_STATE_EOF(strpropEOF):
case YY_STATE_EOF(stringEOF):
#line 392 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		/* Special case for completion mode:
		 *   Compile mode requires TOKEN_EOF, but it must not be intercepted before
		 *   all reductions are done. On the other end, Completion mode needs to
		 *   know the input has no trailing spaces to detect whether the string
		 *   need completion. We return a special EOF token for this purpose,
		 *   and then return the usual TOKEN_EOF. */
		_start_loc (yylloc);
		int start = YY_START;
		BEGIN (parse);
		switch (start) {
			case propEOF:
				return TOKEN_EOF_PROPERTY;
			default:
				return TOKEN_EOF_STRING;
		}
	}
	YY_BREAK


case YY_STATE_EOF(propQ):
case YY_STATE_EOF(strpropQ):
case YY_STATE_EOF(stringQ):
case YY_STATE_EOF(propSQ):
case YY_STATE_EOF(strpropSQ):
case YY_STATE_EOF(stringSQ):
#line 412 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		xcp_scanner_string_buffer_unescape (yyextra);
		yylval->str = xcp_scanner_string_buffer_steal (yyextra);

		/* Malformed pattern: Need closing quote. */
		int start = YY_START;
		BEGIN (parse);
		switch (start) {
			case propQ:
			case propSQ:
				return TOKEN_PROPERTY_EOF_QUOTE;
			case strpropQ:
			case stringQ:
			case strpropSQ:
			case stringSQ:
				return TOKEN_EOF_QUOTE;
			default:
				return TOKEN_ERR;
		}
	}
	YY_BREAK


case 41:
YY_RULE_SETUP
#line 435 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_update_loc (yylloc, yytext);
		BEGIN_STR(Q,);
		break;
	}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 440 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_update_loc (yylloc, yytext);
		xcp_scanner_string_buffer_append (yyextra, yytext);
		break;
	}
	YY_BREAK


case 43:
YY_RULE_SETUP
#line 448 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_update_loc (yylloc, yytext);
		BEGIN_STR(SQ,);
		break;
	}
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 453 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
		_update_loc (yylloc, yytext);
		xcp_scanner_string_buffer_append (yyextra, yytext);
		break;
	}
	YY_BREAK

case 45:
YY_RULE_SETUP
#line 460 "../src/clients/lib/xmmsclient/collparser/scanner.l"
{
	_set_loc (yylloc, yytext);
	printf (">>> %s <<<\n", yytext); /* XXX Should never be reached ? */
	return TOKEN_ERR;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 466 "../src/clients/lib/xmmsclient/collparser/scanner.l"
ECHO;
	YY_BREAK
#line 1700 "<stdout>"
			case YY_STATE_EOF(checkOP):
			case YY_STATE_EOF(propFIL):
			case YY_STATE_EOF(stringFIL):
			case YY_STATE_EOF(strpropFIL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * xcp_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( xcp_yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of xcp_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			xcp_yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) xcp_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	yyg->yy_state_ptr = yyg->yy_state_buf;
	*yyg->yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 149 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yyg->yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 149 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 148);
	if ( ! yy_is_jam )
		*yyg->yy_state_ptr++ = yy_current_state;

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					xcp_yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( xcp_yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void xcp_yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        xcp_yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            xcp_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	xcp_yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	xcp_yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void xcp_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		xcp_yypop_buffer_state();
	 *		xcp_yypush_buffer_state(new_buffer);
     */
	xcp_yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	xcp_yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (xcp_yywrap()) processing, but the only time this flag
	 * is looked at is after xcp_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void xcp_yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE xcp_yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) xcp_yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in xcp_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) xcp_yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in xcp_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	xcp_yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with xcp_yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void xcp_yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		xcp_yyfree((void *) b->yy_ch_buf ,yyscanner );

	xcp_yyfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a xcp_yyrestart() or at EOF.
 */
    static void xcp_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	xcp_yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then xcp_yy_init_buffer was _probably_
     * called from xcp_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void xcp_yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		xcp_yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void xcp_yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	xcp_yyensure_buffer_stack(yyscanner);

	/* This block is copied from xcp_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from xcp_yy_switch_to_buffer. */
	xcp_yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void xcp_yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	xcp_yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		xcp_yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void xcp_yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)xcp_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in xcp_yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)xcp_yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in xcp_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE xcp_yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) xcp_yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in xcp_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	xcp_yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to xcp_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       xcp_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE xcp_yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return xcp_yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to xcp_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE xcp_yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) xcp_yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in xcp_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = xcp_yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in xcp_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE xcp_yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int xcp_yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int xcp_yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *xcp_yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *xcp_yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t xcp_yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *xcp_yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void xcp_yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void xcp_yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "xcp_yyset_lineno called with no buffer" );
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void xcp_yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "xcp_yyset_column called with no buffer" );
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see xcp_yy_switch_to_buffer
 */
void xcp_yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void xcp_yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int xcp_yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void xcp_yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * xcp_yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void xcp_yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *xcp_yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void xcp_yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* xcp_yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int xcp_yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) xcp_yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* xcp_yylex_init_extra has the same functionality as xcp_yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to xcp_yyalloc in
 * the yyextra field.
 */

int xcp_yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    xcp_yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) xcp_yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    xcp_yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from xcp_yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

    yyg->yy_state_buf = 0;
    yyg->yy_state_ptr = 0;
    yyg->yy_full_match = 0;
    yyg->yy_lp = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * xcp_yylex_init()
     */
    return 0;
}

/* xcp_yylex_destroy is for both reentrant and non-reentrant scanners. */
int xcp_yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		xcp_yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		xcp_yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	xcp_yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        xcp_yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    xcp_yyfree ( yyg->yy_state_buf , yyscanner);
    yyg->yy_state_buf  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * xcp_yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    xcp_yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *xcp_yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *xcp_yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void xcp_yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see xcp_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 466 "../src/clients/lib/xmmsclient/collparser/scanner.l"



static void
_start_loc (YYLTYPE *llocp)
{
	llocp->first_line = llocp->last_line;
	llocp->first_column = llocp->last_column;
}

static void
_update_loc (YYLTYPE *llocp, const char *data)
{
	const char *p;
	while ((p = strchr (data, '\n')) != NULL) {
		data = p+1;
		llocp->last_line++;
		llocp->last_column = 1;
	}
	llocp->last_column += strlen(data);
}

static void
_set_loc (YYLTYPE *llocp, const char *data)
{
	_start_loc (llocp);
	_update_loc (llocp, data);
}

void
xcp_scanner_context_init (xmmsv_collparser_t *collparser, const char *input)
{
	xcp_scanner_context_t *ctx;

	/* Clear the previous scanner context. This is required because we can't
	 * reset the internal state of an existing scanner. */
	xcp_scanner_context_free (collparser);

	ctx = collparser->scanner_context = xcp_new0 (xcp_scanner_context_t, 1);

	xcp_yylex_init_extra (collparser, (yyscan_t *)&(ctx->scanner));
	ctx->buffer = xcp_yy_scan_string (input, (yyscan_t) ctx->scanner);
}

void
xcp_scanner_context_free (xmmsv_collparser_t *collparser)
{
	xcp_scanner_context_t *ctx = collparser->scanner_context;

	if (ctx) {
		if (ctx->scanner) {
			if (ctx->buffer) {
				xcp_yy_delete_buffer ((YY_BUFFER_STATE) ctx->buffer,
				                      (yyscan_t) ctx->scanner);
			}
			xcp_yylex_destroy ((yyscan_t) ctx->scanner);
		}
		free (ctx);
	}
}

